### ISSUE TITLE
Better mobile support for ReadTheOrg

### ISSUE THREAD

**Issue by jarvisschultz** [fniessen/org-html-themes#25]
Right now, on a narrow screen the TOC on the left simply covers up the text body. On my Android phone this actually renders the page completely unreadable. The width of the TOC ends up taking the majority of the screen, and I can't read any of the text. I also can't zoom in or out.

On the actual [RTD theme](https://github.com/snide/sphinx_rtd_theme) it automatically switches to a mobile view as the window narrows below a certain pixel value. It seems that the `@media` `max-width` calls are in the `readtheorg.css` file, but things aren't behaving properly.

Sorry to submit a complaint rather than a PR :-1: for me.

**Comment by jarvisschultz** [comment]
Here's a screenshot of a site I made with ReadTheOrg:
![Not Working](https://lh3.googleusercontent.com/F6XNgaTYeHcDU47zTxc1PcXHVnPSQY2T7igPTtb-Q5LK7U8PRk0ZjOfNi2MYjuAmFIqI2YS6Q_J_6iLWv40DY_XxYbA=s853)

Here's a screenshot of a real RTD site:
![Working](https://lh3.googleusercontent.com/--SusbWkPgXQo1LSdhbvN3jV2ELme2McGeq7XNweiYVBpu0-052KvMM5miD6xWKWmOK29XyhoFOD4oLg1UFDBMKNGg=s853)

**Comment by fniessen** [comment]
I know this -- and I don't even know how easy/difficult it is to fix. See note in the **raw** Org file (unluckily it is NOT displayed in the HTML...):

#+begin_note
While the original theme shines on mobile devices as well, ReadTheOrg does not
stay completely functional.

I don't have a lot of time to maintain this project due to other
responsibilities.  Help is welcome to work on that (and eventually improve the
default structure of the HTML export)!
#+end_note

No-one helped here, and I won't have time to look into it in the near feature. Any help appreciated from some CSS guru...

**Comment by jarvisschultz** [comment]
Woohoo! That's great... thanks @geekplux and @fniessen
