### ISSUE TITLE
Raw HTML doesn't appear to work

### ISSUE THREAD

**Issue by mankoff** [fniessen/org-html-themes#41]
Your example doesn't have red text, and as simpler example also appears to have no effect. HTML tags within the `#+HTML_BEGIN:` are also treated as Org text.

    #+HTML_BEGIN: <i>
    Text can be preformatted 
    #+HTML_END: </i>

The above does not render as italic, and a `<b>foo</b>` tag within does not render as bold.

**Comment by fniessen** [comment]
I don't know what you're talking about red text. Please give references.

Regarding what you're trying to perform, it does not work because you're not using a correct syntax (and that has nothing to do with my themes, see http://orgmode.org/manual/Quoting-HTML-tags.html#Quoting-HTML-tags). Use instead:

    #+HTML: <i>
    Text can be preformatted
    #+HTML: </i>

or

    #+BEGIN_HTML
    <i>Text can be preformatted</i>
    #+END_HTML
