### ISSUE TITLE
Date/time stamp in a heading does not display as expected

### ISSUE THREAD

**Issue by doolio** [fniessen/org-html-themes#45]
![image](https://cloud.githubusercontent.com/assets/13859009/18782772/5f484c88-8188-11e6-95a5-d5898833ebe4.png)

Firstly, very much like your theme. In the above image, I would have expected the colour scheme and theme to handle the date/timestamp. With the top line continuing across the timestamp and the grey colour appearing behind the same date/timestamp.

Is this an issue or expected behaviour?

**Comment by fniessen** [comment]
Thanks.

Definitely not the expected behavior.

So, yes, an issue, but not with my theme AFAICT: I've defined `org-date` with the properties `foreground`and `underline` -- so, no `background` defined!

Hence, I suspect this to be either a problem within the font-lock mechanism of Org mode, or with Emacs in general. Trying to get help on the Org mode mailing list could be your best bet right now. I do not see anything in my control to fix this...

**Comment by doolio** [comment]
Thanks for the quick response. I'll seek help on the Org mailing list and report back here if they can resolve it.

**Comment by doolio** [comment]
Sorry I believe I should have raised this issue under your [https://github.com/fniessen/emacs-leuven-theme](url) project rather than here as I was not attempting to export to html specifically but working within an emacs org file with your theme instead.

**Comment by fniessen** [comment]
Thanks for the follow-up. Yes, you should have opened in leuven-theme. Not a big deal.

**Comment by fniessen** [comment]
BTW, please note that it's a generic problem. It's not related to my theme, and it's every time "objects" are surimposed. Note, for example, the same problem with URL in tables...
