### ISSUE TITLE
GPL License is an issue - as potentially 'taints' private content.

### ISSUE THREAD

**Issue by timoc** [fniessen/org-html-themes#49]
Why does it even need GPL? LGPL might be applicable, but that means i may have to publish my own private styles based on this, and potentially the content as well.

**Comment by fniessen** [comment]
I have followed what I needed to choose for a couple of other projects linked to Emacs (leuven-theme, Org mode, etc.).

Now, I may consider changing it if there are good reasons for it... but I'm not a specialist on those issues. Could you point me to a good summary on this?  Thanks.

**Comment by Nebucatnetzer** [comment]
I think it this would only be necessary if you publicly publish something. If you keep things private nobody will care about the license you're using.

**Comment by fniessen** [comment]
The main idea here is that, as it is public, it needs to be clear what people can do with it, such as use it, modify it, republish it on other sites, etc.

That's why I think having a clear statement is better than nothing.

Now, I'm ready to learn if the current chosen licence is not the right one.

**Comment by Nebucatnetzer** [comment]
Sure for the project it makes of course sense.
My comment was more meant for timoc.
If he doesn't make his notes publicly accessible then he won't have to
share anything.
And when he does make it public, the code which makes the website is open anyway or isn't it?
